### ISSUE TITLE
Exported model's UV becomes broken

### ISSUE THREAD

**Issue by knabsi** [Brachi/albam#51]
### Game

Resident Evil 5

### Example game file names

Any .arc

### Blender version

2.79

### Albam version

0.3.0-testing (albam-bugfix-ISSUE-47-original-model-deformed-after-export)

### Observed behavior

UV map is broken after export.
![f](https://user-images.githubusercontent.com/31842577/30761821-f9b0a876-9fdf-11e7-8ed7-7c6491ff7a7d.jpg)

### Expected behavior

UV map should be the same as it is in Blender.

### Steps to reproduce

Export a custom model with textures and UV map.

**Comment by EvTital** [comment]
You can fix this issue by marking the seams as "sharp edges" and splitting those hard edges.
+ It fixes the broken UV on import.
- You get hard edges.

**Comment by Brachi** [comment]
Work-around in [Albam Reloaded](https://github.com/henryofcarim/albam_reloaded) via `Tools -> Fix leaked textures`. The bug is in the export code, because vertices are not duplicated when they contain multiple attributes. If in Blender a vertex has more than one pair of UVs, in DirectX and GPUs expect a duplicate vertex.
This is way at import time with original models one can almost always eliminate duplicate vertices merging by distance.
I'll track this in a new issue from the roadmap.
